name: Publish MZSimpleDynamicLinq.EFCoreExtensions NuGet Package

on:
  push:
    paths:
      - 'MZSimpleDynamicLinq.EFCoreExtensions/**'
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MZSimpleDynamicLinq.EFCoreExtensions/MZSimpleDynamicLinq.EFCoreExtensions.csproj

    - name: Build
      run: dotnet build --configuration Release MZSimpleDynamicLinq.EFCoreExtensions/MZSimpleDynamicLinq.EFCoreExtensions.csproj

    - name: Pack
      run: dotnet pack --configuration Release --output ./nupkg MZSimpleDynamicLinq.EFCoreExtensions/MZSimpleDynamicLinq.EFCoreExtensions.csproj

    - name: Publish NuGet package
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate
